require("settings")
require("keymaps")
require("dependencies")
require("commands")

require("autopairs")
require("bottomline")
require("syntax-highlighting")
require("file-explorer")
require("npm")
require("git")

require("comments").init()
require("indexing").init()
require("lsp").init()
require("code-completion").init()
require("start-screen")
require("projects")
require("plugins")

